import React, { useState } from "react";
import { useAuth } from "../context/AuthContext.jsx";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Eye, EyeOff } from "lucide-react";
import { Link } from "react-router-dom";
import GoogleAuth from '../components/GoogleAuth.jsx';

export default function Signup() {
  const [formData, setFormData] = useState({
    fullName: "",
    email: "",
    password: "",
    role: "User",
    bio: "",
  });

  const [generatedId, setGeneratedId] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const { signup } = useAuth();
  const navigate = useNavigate();

  // Handle form input changes
  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Generate unique user ID based on role
  // ID now generated by server; keep local state to display what was returned

  // Form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    try {
      setLoading(true);
  const res = await signup({ fullName: formData.fullName, email: formData.email, password: formData.password, role: formData.role, bio: formData.bio });
  setGeneratedId(res.id);
      setShowModal(true);
      setFormData({ fullName: "", email: "", password: "", role: "User", bio: "" });
  // After a brief pause or modal acknowledgement, route to login
  setTimeout(() => navigate('/login'), 800);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="form-container">
      <button
        type="button"
        onClick={() => navigate(-1)}
        style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          background: '#b30000', color: '#fff', padding: '8px 12px',
          borderRadius: 8, border: 'none', cursor: 'pointer', marginBottom: 12
        }}
        aria-label="Go back"
      >
        <ArrowLeft size={18} /> Back
      </button>
      <h2>Sign Up</h2>
      <form onSubmit={handleSubmit} autoComplete="off">
        <input
          type="text"
          name="fullName"
          placeholder="Full Name"
          value={formData.fullName}
          onChange={handleChange}
          autoComplete="off"
          required
        />
        <input
          type="email"
          name="email"
          placeholder="Email"
          value={formData.email}
          onChange={handleChange}
          autoComplete="off"
          required
        />
        <div style={{ position:'relative' }}>
          <input
            type={showPassword ? 'text' : 'password'}
            name="password"
            placeholder="Password"
            value={formData.password}
            onChange={handleChange}
            required
            autoComplete="new-password"
            style={{ width:'100%', paddingRight:42 }}
          />
          <button
            type="button"
            aria-label={showPassword ? 'Hide password' : 'Show password'}
            onClick={() => setShowPassword(v => !v)}
            style={{ position:'absolute', right:8, top:'50%', transform:'translateY(-50%)', background:'transparent', border:'none', padding:6, cursor:'pointer', color:'#374151', zIndex:2 }}
          >
            {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
          </button>
        </div>
        <select name="role" value={formData.role} onChange={handleChange}>
          <option>User</option>
          <option>Judge</option>
          <option>Lawyer</option>
          <option>Police</option>
          <option>Registrar</option>
        </select>
        <textarea
          name="bio"
          placeholder="Write a short bio..."
          value={formData.bio}
          onChange={handleChange}
          rows="3"
        />
  {error && <div style={{ color: 'red' }}>{error}</div>}
  <button type="submit" disabled={loading}>{loading ? 'Signing up...' : 'Sign Up'}</button>
      </form>
      <div className="separator">OR</div>
      <GoogleAuth isSignup={true} />

      {showModal && (
        <div className="modal">
          <div className="modal-content">
            <h3>Your ID has been generated!</h3>
            <p>
              <strong>{generatedId}</strong>
            </p>
            <button onClick={() => setShowModal(false)}>Close</button>
          </div>
        </div>
      )}
      <div style={{ marginTop: '12px', fontSize: '14px' }}>
        Already have an account? <Link to="/login" style={{ color: '#0077cc', textDecoration: 'underline' }}>Login</Link>
      </div>
    </div>
  );
}
